# Welcome message when a player enters the server
welcome_message: Welcome %playername%~
# End of round message
round_end_info: The round is over! Dont leave, see you next timeヾ(￣▽￣)~
# Messages players will receive when friendly damage is turned on
f_f_message: <align=center><voffset=28em> <color=#F6511D> ~Friendly damage is turned on~ </color></voffset></align>
# Server broadcast text
auto_server_message_text: Server broadcast
# Administrator monitoring output text
admin_log: '%Nickname% at %Time% | Used command: %Command% | Steam64ID: %UserId%'
# Administrator monitoring command broadcast
admin_log_broadcast: '<size=30>[<color=red>Admin behavior monitoring output record</color>] <%Nickname%> Just used command: %Command%</size>'
# Display the time left before startup and the server status
title_text: <size=50><color=#F0FF00><b>Waiting for players, {seconds}</b></color></size>
# Text to display the number of players
player_count_text: <size=40><color=#FFA600><i>{players}</i></color></size>
# Message to display if the lobby is locked
server_pause_text: Server paused
# Message on the second line
second_left_text: {seconds} left
# Message on multiple lines
seconds_left_text: {seconds} left
# Message to display when a round starts
round_start_text: Round starts
# Message to display when a player joins the server
player_join_text: Player joins
# Message to display when multiple players join the server
players_join_text: Players join
# Announcement to display when a guard mutinies
guard_mutiny_broadcast: <size=60><color=#ff0000ff>[Warning]</color>This facility guard has been turned against by the Chaos Insurgency</size>
# Announcement to display when a guard is an elite team
elite_guard_broadcast: <size=60><color=#00ffffff>[Notice]</color>The guards of this facility are the elite members of the Nine-Tailed Fox, and the security strength has been greatly improved</size>
# Watch list title
watch_list_title: <align=right><size=45%><color=(COLOR)><b>Observer ((COUNT)):</b></color></size></align>
# Watch list format
names: <align=right><size=45%><color=(COLOR)><br>(NAME)</color></size></align>
# DNT reminder
d_n_t_warning: You have turned on DNT, please turn it off, otherwise some plug-ins will not work properly
# SCP-073 reverse injury reason
s_c_p073_damage_reason: SCP073 reverse injury
# SCP-029 escape facility Hint
s_c_p029_escape_hint: Successfully escape the facility and become Chaos to get a legacy of the Chaos Insurgency
# SCP-703 escape facility Hint
s_c_p703_escape_hint: Successfully escape the facility to become a Nine-Tailed Fox Containment Expert, and get 3x
# Skynet Mobile Task Force Cassie Broadcast
skynet_cassie: Mobile Task Force Kappa-10 and Mu-7 codenamed Skynet have entered the facility. They will help Dancer One contain SCP-079. It is recommended that all surviving personnel implement standard evacuation plans until the MTF team arrives at your location. There are currently %SCPNum% SCPs left
# Skynet Mobile Task Force New Recruit Broadcast
skynet_private_broadcast: <size=70><color=#0051FF>You are a Mobile Task Force-Skynet New Recruit</color></size>
# Skynet Mobile Task Force New Recruit Custom Information
skynet_private_custom_info: Skynet New Recruit
# Skynet Mobile Task Force Sergeant Broadcast
skynet_sergeant_broadcast: <size=70><color=#0051FF>You are a Sergeant of Mobile Task Force-Skynet</color></size>
# Skynet Mobile Task Force Recruit Custom Info
skynet_sergeant_custom_info: Skynet Sergeant
# Skynet Mobile Task Force Commander Broadcast
skynet_captain_broadcast: <size=70><color=#0051FF>You are a Commander of Mobile Task Force-Skynet</color></size>
# Skynet Mobile Task Force Commander Custom Info
skynet_captain_custom_info: Skynet Commander
# See No Evil Mobile Task Force Cassie Broadcast
see_no_evil_cassie: Mobile Task Force Eta-10 codenamed See No Evil has entered the facility. They will help contain SCP-096. It is recommended that all surviving personnel follow the standard evacuation plan until the MTF team reaches your location. There are currently %SCPNum% SCPs left
# See No Evil Mobile Task Force New Recruit Broadcast
see_no_evil_private_broadcast: <size=70><color=#0051FF>You are a Mobile Task Force-See No Evil New Recruit</color></size>
# See No Evil Mobile Task Force New Recruit Custom Information
see_no_evil_private_custom_info: See No Evil New Recruit
# See No Evil Mobile Task Force Sergeant Broadcast
see_no_evil_sergeant_broadcast: <size=70><color=#0051FF>You are a Mobile Task Force-See No Evil Sergeant</color></size>
# See No Evil Mobile Task Force New Recruit Custom Information
see_no_evil_sergeant_custom_info: See No Evil Sergeant
# See No Evil Mobile Task Force Commander Broadcast
see_no_evil_captain_broadcast: <size=70><color=#0051FF>You are the commander of Mobile Task Force-See No Evil</color></size>
# See No Evil Mobile Task Force commander custom information
see_no_evil_captain_custom_info: See No Evil Commander
# Special role contained Cassie suffix
special_role_contain_cassie: Successfully eliminated, the specific reason is unknown
# Chaos leader name
chaos_leader_role_name: Chaos Leader
# Chaos leader refresh broadcast
chaos_leader_spawn_broadcast: <size=80><color=#00ff00ff>You are Chaos Insurgency leader</color></size>
# Chaos leader dies Cassie
chaos_leader_death_cassie: Chaos leader dies
# SCP-2936-1 refresh broadcast
s_c_p29361_spawn_broadcast: <size=70>You are <color=red>SCP-2936-1 Giant German Robot</color></size>
# SCP-073 Abel refresh broadcast
s_c_p073_abel_spawn_broadcast: You are <color=green>SCP-073 Abel</color>
# SCP-073 refresh broadcast
s_c_p073_cain_spawn_broadcast: You are <color=green>SCP-073 Cain</color>
# SCP-703 refresh broadcast
s_c_p703_spawn_broadcast: <size=80><color=#00ffffff>You are SCP-703</color></size>
# SCP-703 skill introduction
s_c_p703_skill_introduction: <align=center><voffset=28em><size=70><color=#00ffffff>You will get a random item every once in a while</color></size></voffset></align>
# SCP-703 received item Hint
s_c_p703_received_item_hint: received an item
# SCP-029 refresh broadcast
s_c_p029_spawn_broadcast: <size=60><color=#ff0000ff>You are SCP-029 Daughter of Shadow</color></size>
# SCP-029 skill introduction
s_c_p029_skill_introduction: <voffset=28em><size=40><color=#ff0000ff>Kill all your enemies</color></size></voffset>
# SCP-347 refresh broadcast
s_c_p347_spawn_broadcast: You are <color=red>SCP-347 Invisible Woman</color>
# SCP-1093 refresh broadcast
s_c_p1093_spawn_broadcast: You are <color=yellow>SCP-1093 Human Light</color>
# SCP-1093 Skill Introduction
s_c_p1093_skill_introduction: >-Continuously illuminates the surrounding 5 meters, and affects people within 1 meter of the surrounding area to receive radiation damage (1 health loss per second) Your head seems to be empty, so no one can hurt your head
# Guard Captain refreshes broadcast
guard_captain_spawn_broadcast: <size=60><color=#E5DADA>You are the security captain</color></size>
# SCP-191 refreshes broadcast
s_c_p191_spawn_broadcast: You have become <color=red>SCP-191 Mechanical Girl</color>
# SCP-191 Skill Introduction
s_c_p191_skill_introduction: Because of your body modification, you are highly resistant to damage except electromagnetic and explosive
# SCP-191 battery display
s_c_p191_battery_hint_show: <align=right><size=60><b>Your current remaining battery: <color=yellow>%Battery%A</color></size></b></align>
# SCP-1056 Miniaturizer Pickup Hint
s_c_p1056_pickup_hint: You picked up the <color=red>SCP-1056</color> Miniaturizer!
# SCP-1056 Miniaturizer Use Hint
s_c_p1056_used_hint: boom! Youve become smaller!!!
# SCP-1068 Harmless Nuclear Bomb Pickup Hint
s_c_p1068_pickup_hint: You picked up the <color=red>SCP-1068</color> Harmless Nuclear Bomb!
# SCP-1056 Harmless Nuclear Bomb Used Broadcast
s_c_p1068_used_broadcast: Someone used the <color=red>SCP-1068</color> harmless nuclear bomb!
