# 玩家信息指令_标题
info_command_title: "自从插件安装后你已在本服游玩了";
# 玩家信息指令_时间
info_command_played_time: "<color=red>%day%</color>天<color=red>%hour%</color>小时<color=red>%minutes%</color>分钟";
# 玩家信息指令_角色
info_command_role_played: "一共扮演了<color=red>%rolePlayed%</color>次角色";
# 玩家信息指令_击杀和伤害
info_command_kills_damages: "你一共击杀了<color=red>%kills%</color>个人<color=red>%scpKills%</color>个SCP | 一共造成了<color=red>%playerDamage%</color>点伤害(伤害包括无效的) | 一共死亡<color=red>%playerDeath%次</color>";
# 玩家信息指令_射击
info_command_shot: "一共开了<color=red>%shot%</color>枪";
# 玩家信息指令_因DNT查询失败的消息
info_command_failed: "查询失败,请关闭DNT或服务器未启用此功能";